blueprint:
  name: IKEA Bilresa (Remote with scroll) - Smart Light Control
  description: |
    Control your lights with the IKEA Bilresa(Remote with scroll) via Matter.
    
    **Features:**
    - 3 independent groups (9 buttons total)
    - Left/Right buttons: dim up/down
    - Middle button: toggle on/off
    - Middle button long press: cycle color temperature (warm → neutral → cool)
    
    **Button Layout:**
    - Buttons 1-3: Group 1
    - Buttons 4-6: Group 2  
    - Buttons 7-9: Group 3
    
    Select corresponding button ID (1-9) for each button input.
    Button 1 = button 1 for correct remote, button 2 = button 2, etc.


    Group 1 Light: The first light/output you want to control with first group of buttons. Scroll, on/off, longhold for changing color temp.
    And so on.

    Brightness Step for how much each scroll step should change brightness (in percent).
    Transition Time for smooth brightness changes (in seconds).
    Color Temperatures (in Kelvin) for warm, neutral and cool white.

    **Setup:** Find your button entities in Developer Tools → States, they look like "event.your_remote_name_button_1" through "button_9"
    
  domain: automation
  
  input:
    button_1:
      name: Button 1
      selector:
        entity:
          filter:
            - domain: event
    button_2:
      name: Button 2
      selector:
        entity:
          filter:
            - domain: event
    button_3:
      name: Button 3
      selector:
        entity:
          filter:
            - domain: event
    button_4:
      name: Button 4
      selector:
        entity:
          filter:
            - domain: event
    button_5:
      name: Button 5
      selector:
        entity:
          filter:
            - domain: event
    button_6:
      name: Button 6
      selector:
        entity:
          filter:
            - domain: event
    button_7:
      name: Button 7
      selector:
        entity:
          filter:
            - domain: event
    button_8:
      name: Button 8
      selector:
        entity:
          filter:
            - domain: event
    button_9:
      name: Button 9
      selector:
        entity:
          filter:
            - domain: event
    
    control_mode:
      name: Control Mode
      description: |
        **Event Mode**: Uses button events (supports long-press for color temp)
        **Sensor Mode**: Uses switch position sensors (faster brightness response)
      default: event
      selector:
        select:
          options:
            - label: Event Mode (with long-press)
              value: event
            - label: Sensor Mode (faster)
              value: sensor
    
    sensor_position_1:
      name: Switch Position Sensor 1
      description: Only needed for Sensor Mode
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor
    
    sensor_position_2:
      name: Switch Position Sensor 2
      description: Only needed for Sensor Mode
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor
    
    sensor_position_3:
      name: Switch Position Sensor 3
      description: Only needed for Sensor Mode
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor
    
    sensor_position_4:
      name: Switch Position Sensor 4
      description: Only needed for Sensor Mode
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor
    
    sensor_position_5:
      name: Switch Position Sensor 5
      description: Only needed for Sensor Mode
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor
    
    sensor_position_6:
      name: Switch Position Sensor 6
      description: Only needed for Sensor Mode
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor
    
    sensor_position_7:
      name: Switch Position Sensor 7
      description: Only needed for Sensor Mode
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor
    
    sensor_position_8:
      name: Switch Position Sensor 8
      description: Only needed for Sensor Mode
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor
    
    sensor_position_9:
      name: Switch Position Sensor 9
      description: Only needed for Sensor Mode
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor
    
    group1_light:
      name: Group 1 Light (Buttons 1-3)
      description: Light(s) controlled by buttons 1-3
      selector:
        entity:
          filter:
            - domain: light
    
    group2_light:
      name: Group 2 Light (Buttons 4-6)
      description: Light(s) controlled by buttons 4-6
      selector:
        entity:
          filter:
            - domain: light
    
    group3_light:
      name: Group 3 Light (Buttons 7-9)
      description: Light(s) controlled by buttons 7-9
      selector:
        entity:
          filter:
            - domain: light
    
    brightness_step:
      name: Brightness Step
      description: Percentage to increase/decrease brightness per button press
      default: 10
      selector:
        number:
          min: 5
          max: 25
          step: 5
          unit_of_measurement: "%"
    
    transition_time:
      name: Transition Time
      description: Smooth transition duration for brightness changes
      default: 1
      selector:
        number:
          min: 0
          max: 5
          step: 1
          unit_of_measurement: "s"
    
    temp_warm:
      name: Warm Color Temperature
      description: Warm white color temperature in Kelvin
      default: 2700
      selector:
        number:
          min: 2000
          max: 3500
          step: 100
          unit_of_measurement: "K"
    
    temp_neutral:
      name: Neutral Color Temperature
      description: Neutral white color temperature in Kelvin
      default: 4000
      selector:
        number:
          min: 3500
          max: 5000
          step: 100
          unit_of_measurement: "K"
    
    temp_cool:
      name: Cool Color Temperature
      description: Cool white color temperature in Kelvin
      default: 6000
      selector:
        number:
          min: 5000
          max: 7000
          step: 100
          unit_of_measurement: "K"

mode: restart
max_exceeded: silent

trigger:
  # Event-based triggers (for Event Mode)
  - platform: state
    entity_id: !input button_1
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
    id: btn1
  - platform: state
    entity_id: !input button_2
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
    id: btn2
  - platform: state
    entity_id: !input button_3
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
    id: btn3
  - platform: state
    entity_id: !input button_4
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
    id: btn4
  - platform: state
    entity_id: !input button_5
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
    id: btn5
  - platform: state
    entity_id: !input button_6
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
    id: btn6
  - platform: state
    entity_id: !input button_7
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
    id: btn7
  - platform: state
    entity_id: !input button_8
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
    id: btn8
  - platform: state
    entity_id: !input button_9
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
    id: btn9
  
  # Sensor-based triggers (for Sensor Mode)
  - platform: state
    entity_id: !input sensor_position_1
    to: "1"
    id: sensor1
  - platform: state
    entity_id: !input sensor_position_2
    to: "2"
    id: sensor2
  - platform: state
    entity_id: !input sensor_position_3
    to: "3"
    id: sensor3
  - platform: state
    entity_id: !input sensor_position_4
    to: "4"
    id: sensor4
  - platform: state
    entity_id: !input sensor_position_5
    to: "5"
    id: sensor5
  - platform: state
    entity_id: !input sensor_position_6
    to: "6"
    id: sensor6
  - platform: state
    entity_id: !input sensor_position_7
    to: "7"
    id: sensor7
  - platform: state
    entity_id: !input sensor_position_8
    to: "8"
    id: sensor8
  - platform: state
    entity_id: !input sensor_position_9
    to: "9"
    id: sensor9

action:
  - variables:
      group1: !input group1_light
      group2: !input group2_light
      group3: !input group3_light
      warm_temp: !input temp_warm
      neutral_temp: !input temp_neutral
      cool_temp: !input temp_cool
      step_pct: !input brightness_step
      trans_time: !input transition_time
      mode: !input control_mode
      is_sensor_mode: "{{ mode == 'sensor' }}"
      is_event_mode: "{{ mode == 'event' }}"
      trigger_type: "{{ trigger.id.split('|')[0] if '|' in trigger.id else trigger.id[:6] if trigger.id.startswith('sensor') else trigger.id[:3] }}"
      target_light: >
        {% if trigger.id in ['btn1', 'btn2', 'btn3', 'sensor1', 'sensor2', 'sensor3'] %}
          {{ group1 }}
        {% elif trigger.id in ['btn4', 'btn5', 'btn6', 'sensor4', 'sensor5', 'sensor6'] %}
          {{ group2 }}
        {% else %}
          {{ group3 }}
        {% endif %}
      is_long: "{{ trigger.to_state.attributes.event_type == 'long_press' if not is_sensor_mode else false }}"
  
  # Mode-specific validation
  - condition: template
    value_template: >
      {% if is_event_mode %}
        {{ trigger.id.startswith('btn') and 
           trigger.to_state.attributes.event_type is defined and 
           trigger.to_state.attributes.event_type != none }}
      {% else %}
        {{ trigger.id.startswith('sensor') }}
      {% endif %}
  
  # Prevent stale events (event mode only)
  - condition: template
    value_template: >
      {% if is_event_mode %}
        {{ (now() - trigger.to_state.last_changed).total_seconds() < 5 and
           (now() - (trigger.to_state.state | as_datetime | as_local)).total_seconds() < 5 }}
      {% else %}
        {{ (now() - trigger.to_state.last_changed).total_seconds() < 2 }}
      {% endif %}
  
  - choose:
      # Long press for color temperature cycling (Event Mode only)
      - conditions:
          - condition: template
            value_template: "{{ is_event_mode and is_long and trigger.id in ['btn3', 'btn6', 'btn9'] }}"
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              color_temp_kelvin: >
                {% set current = state_attr(target_light, 'color_temp_kelvin') | int(warm_temp) %}
                {% if current < neutral_temp %}
                  {{ neutral_temp }}
                {% elif current < cool_temp %}
                  {{ cool_temp }}
                {% else %}
                  {{ warm_temp }}
                {% endif %}
      
      # Toggle middle button (both modes)
      - conditions:
          - condition: template
            value_template: >
              {{ (is_event_mode and trigger.id in ['btn3', 'btn6', 'btn9'] and not is_long) or
                 (is_sensor_mode and trigger.id in ['sensor3', 'sensor6', 'sensor9']) }}
        sequence:
          - action: light.toggle
            target:
              entity_id: "{{ target_light }}"
      
      # Brightness up (left buttons/positions)
      - conditions:
          - condition: template
            value_template: >
              {{ (is_event_mode and trigger.id in ['btn1', 'btn4', 'btn7']) or
                 (is_sensor_mode and trigger.id in ['sensor1', 'sensor4', 'sensor7']) }}
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              brightness_step_pct: "{{ step_pct }}"
              transition: "{{ trans_time }}"
      
      # Brightness down (right buttons/positions)
      - conditions:
          - condition: template
            value_template: >
              {{ (is_event_mode and trigger.id in ['btn2', 'btn5', 'btn8']) or
                 (is_sensor_mode and trigger.id in ['sensor2', 'sensor5', 'sensor8']) }}
        sequence:
          - action: light.turn_on
            target:
              entity_id: "{{ target_light }}"
            data:
              brightness_step_pct: "{{ 0 - step_pct }}"
              transition: "{{ trans_time }}"