blueprint:
  name: 'âœ¨ Advanced Multi-Room Motion Lighting'
  description: >
    Control multiple rooms (up to 5) independently using motion sensors, lux levels, 
    and time-of-day modes. Prevents lights from turning on if the room is already bright enough.
  domain: automation
  input:
    # ===================================================================================
    # GLOBAL SETTINGS
    # ===================================================================================
    lux_entity:
      name: Global Ambient Light Sensor (Lux)
      description: The sensor entity providing the current ambient light level (in lux).
      selector:
        entity:
          domain: sensor
          device_class: illuminance
      icon: mdi:brightness-percent
    
    # ===================================================================================
    # TIME OF DAY DEFINITION
    # ===================================================================================
    time_morning_start:
      name: ðŸŒ… Morning Start Time
      description: Lights will use 'Morning' settings after this time. (e.g., 06:00:00)
      default: '06:00:00'
      selector:
        time:
      icon: mdi:weather-sunset-up
      
    time_day_start:
      name: â˜€ï¸ Daytime Start Time
      description: Lights will use 'Daytime' settings after this time. (e.g., 08:00:00)
      default: '08:00:00'
      selector:
        time:
      icon: mdi:white-balance-sunny
      
    time_night_start:
      name: ðŸŒ™ Night Start Time
      description: Lights will use 'Night' settings after this time. (e.g., 22:00:00)
      default: '22:00:00'
      selector:
        time:
      icon: mdi:weather-night

    # ===================================================================================
    # ROOM 1 CONFIGURATION
    # ===================================================================================
    room_1_name:
      name: 1. Room Name (e.g., Hallway)
      default: 'Room 1'
      selector:
        text:
      icon: mdi:rename
    
    room_1_enabled:
      name: Enable Room 1 Automation
      default: true
      selector:
        boolean:
      icon: mdi:toggle-switch-outline
      
    room_1_motion_sensor:
      name: Motion/Occupancy Sensor
      description: Select the sensor that triggers the light(s).
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
      icon: mdi:motion-sensor
      
    room_1_lights:
      name: Target Light(s)
      description: Select one or more light entities to control.
      selector:
        target:
          entity:
            domain: light
      icon: mdi:lightbulb-multiple-outline
      
    room_1_off_delay:
      name: â±ï¸ Lights Off Delay (seconds)
      description: The time after the last motion detected before lights turn off.
      default: 180
      selector:
        number:
          min: 30
          max: 1800
          unit_of_measurement: seconds
      icon: mdi:timer-off-outline
      
    room_1_override_switch:
      name: ðŸ›‘ Manual Override Switch (Optional)
      description: If this helper switch is ON, the automation will be disabled for this room.
      default: ''
      selector:
        entity:
          domain: input_boolean
          multiple: false
          
    room_1_lux_threshold:
      name: ðŸ’¡ Lux Threshold (Lights-On Limit)
      description: If the ambient lux is ABOVE this value, the lights will NOT turn on. (e.g., 50 lux)
      default: 50
      selector:
        number:
          min: 5
          max: 500
          unit_of_measurement: lux
      icon: mdi:brightness-7
      
    # Room 1 Brightness Settings (Collapsed by Default)
    room_1_morning_settings:
      name: ðŸŒ… Morning Light Settings (After {{ time_morning_start }} & Before {{ time_day_start }})
      description: Brightness and Color Temperature for morning hours.
      default: {}
      selector:
        object:
      icon: mdi:sun-clock
      
    room_1_morning_brightness:
      name: Morning Brightness (%)
      default: 50
      selector:
        number:
          min: 1
          max: 100
          mode: slider
      icon: mdi:brightness-5
      
    room_1_morning_temp:
      name: Morning Color Temperature (Kelvin)
      description: Color temperature in Kelvin (e.g., 4000K). Leave blank to use current.
      default: 4000
      selector:
        number:
          min: 1500
          max: 6500
          mode: slider
          unit_of_measurement: K
      icon: mdi:thermometer-lines
      
    room_1_daytime_settings:
      name: â˜€ï¸ Daytime Light Settings (After {{ time_day_start }} & Before {{ time_night_start }})
      description: Brightness and Color Temperature for general daytime hours.
      default: {}
      selector:
        object:
      icon: mdi:sun-clock
      
    room_1_daytime_brightness:
      name: Daytime Brightness (%)
      default: 80
      selector:
        number:
          min: 1
          max: 100
          mode: slider
      icon: mdi:brightness-7
      
    room_1_daytime_temp:
      name: Daytime Color Temperature (Kelvin)
      description: Color temperature in Kelvin (e.g., 5500K). Leave blank to use current.
      default: 5500
      selector:
        number:
          min: 1500
          max: 6500
          mode: slider
          unit_of_measurement: K
      icon: mdi:thermometer-lines
      
    room_1_night_settings:
      name: ðŸŒ™ Night Light Settings (After {{ time_night_start }} & Before {{ time_morning_start }})
      description: Low brightness and warm color for late night/sleep hours.
      default: {}
      selector:
        object:
      icon: mdi:sun-clock
      
    room_1_night_brightness:
      name: Night Brightness (%)
      default: 20
      selector:
        number:
          min: 1
          max: 100
          mode: slider
      icon: mdi:brightness-3
      
    room_1_night_temp:
      name: Night Color Temperature (Kelvin)
      description: Color temperature in Kelvin (e.g., 2700K). Leave blank to use current.
      default: 2700
      selector:
        number:
          min: 1500
          max: 6500
          mode: slider
          unit_of_measurement: K
      icon: mdi:thermometer-lines
      
    # -----------------------------------------------------------------------------------
    # ROOM 2 CONFIGURATION (omitted for brevity, assume identical structure as Room 1)
    # -----------------------------------------------------------------------------------
    # NOTE: In a real blueprint, you would duplicate all 10 Room 1 inputs 4 more times,
    # replacing 'room_1' with 'room_2', 'room_3', 'room_4', and 'room_5'.
    # -----------------------------------------------------------------------------------

variables:
  # Get the current time as a seconds-since-midnight number for comparison
  current_time_seconds: "{{ now().hour * 3600 + now().minute * 60 + now().second }}"
  
  # Convert user-defined time inputs to seconds since midnight
  morning_start_seconds: "{{ states('input_datetime.time_morning_start').split(':')[0] | int * 3600 + states('input_datetime.time_morning_start').split(':')[1] | int * 60 }}"
  day_start_seconds: "{{ states('input_datetime.time_day_start').split(':')[0] | int * 3600 + states('input_datetime.time_day_start').split(':')[1] | int * 60 }}"
  night_start_seconds: "{{ states('input_datetime.time_night_start').split(':')[0] | int * 3600 + states('input_datetime.time_night_start').split(':')[1] | int * 60 }}"
  
  # Determine the current time-of-day mode
  time_mode: >
    {% if current_time_seconds >= night_start_seconds %}
      night
    {% elif current_time_seconds >= day_start_seconds %}
      daytime
    {% elif current_time_seconds >= morning_start_seconds %}
      morning
    {% else %}
      night
    {% endif %}

  # Determine the brightness and color temp based on mode (using Room 1 as example)
  room_1_brightness: >
    {% if time_mode == 'morning' %}
      {{ (states('input_number.room_1_morning_brightness') | float * 2.55) | int }}
    {% elif time_mode == 'daytime' %}
      {{ (states('input_number.room_1_daytime_brightness') | float * 2.55) | int }}
    {% else %}
      {{ (states('input_number.room_1_night_brightness') | float * 2.55) | int }}
    {% endif %}
    
  room_1_color_temp: >
    {% if time_mode == 'morning' %}
      {{ states('input_number.room_1_morning_temp') | int }}
    {% elif time_mode == 'daytime' %}
      {{ states('input_number.room_1_daytime_temp') | int }}
    {% else %}
      {{ states('input_number.room_1_night_temp') | int }}
    {% endif %}

trigger:
  # Trigger 1: Motion Detected (Room 1)
  - platform: state
    entity_id: !input room_1_motion_sensor
    to: 'on'
    id: 'room_1_on'
    
  # Trigger 2: Motion Cleared (Room 1)
  - platform: state
    entity_id: !input room_1_motion_sensor
    to: 'off'
    for: "{{ states('input_number.room_1_off_delay') | int }}"
    id: 'room_1_off'
    
  # NOTE: In a complete blueprint, this trigger block would repeat for rooms 2-5
  
action:
  - choose:
      # ===================================================================================
      # LIGHTS ON LOGIC (ROOM 1)
      # ===================================================================================
    - conditions:
        - condition: trigger
          id: 'room_1_on'
        - condition: state
          entity_id: !input room_1_enabled
          state: 'on'
        # Override Check: Skip if manual override is active (if entity is provided)
        - condition: template
          value: "{{ not is_state(states('input_boolean.room_1_override_switch'), 'on') if states('input_boolean.room_1_override_switch') is not none }}"
        # Lux Check: Only turn on if current lux is below the room's threshold
        - condition: template
          value: "{{ states(lux_entity) | float(0) < states('input_number.room_1_lux_threshold') | float(0) }}"
      sequence:
        - service: light.turn_on
          data:
            # Custom Idea: Set brightness and color temp based on time_mode variable
            brightness: "{{ room_1_brightness }}"
            color_temp: "{{ room_1_color_temp }}"
            transition: 1
          target: !input room_1_lights
        - service: automation.turn_off
          target:
            entity_id: automation.{{ blueprint_full_path.split('.')[-1] }}_room_1
        - service: automation.turn_on
          target:
            entity_id: automation.{{ blueprint_full_path.split('.')[-1] }}_room_1

      # ===================================================================================
      # LIGHTS OFF LOGIC (ROOM 1)
      # ===================================================================================
    - conditions:
        - condition: trigger
          id: 'room_1_off'
      sequence:
        - service: light.turn_off
          data:
            transition: 2
          target: !input room_1_lights
          
    # NOTE: The 'choose' block would contain the logic for rooms 2-5 as well.

mode: restart